export {default as MoviesPage} from './MoviesPage'
export {default as ErrorPage} from './ErrorPage'
export {default as EmptyPage} from './EmptyPage'
export {default as MovieDetailPage} from './MovieDetailPage'
export {default as SearchPage} from './SearchPage'